name: compression
dependencies:
  - python=3.10.10
  - pip=23.3.1
  - pip:
    - transformers==4.37.2
    - seaborn==0.13.2
    - scikit-learn==1.4.0
    - pandas==2.2.1
    - GitPython==3.1.43
    - torch==2.2.2
    - evaluate==0.4.2
    - accelerate==0.27.0
    - absl-py==2.1.0
    - nltk==3.8.1
    - rouge_score==0.1.2
